
apiVersion: v1
kind: Service
metadata:
  name: minio-demo-app
  namespace: demo-minio-jfrog
spec:
  selector:
    app: minio-demo-app
  ports:
    - name: http
      port: 80           # Service port
      targetPort: http   # Container port
  type: ClusterIP
