
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: demo-minio-jfrog
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000        # Service port for S3 API
      targetPort: api   # Maps to containerPort named "api"
    - name: console
      port: 9001        # Service port for Web console
      targetPort: console
  type: ClusterIP       # Internal-only; we'll use kubectl port-forward
