apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: demo-minio-jfrog
type: Opaque
data:
  # base64("minioadmin")
  accesskey: bWluaW9hZG1pbg==
  # base64("minioadmin123")
  secretkey: bWluaW9hZG1pZG0xMjM=
