apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: demo-minio-jfrog
spec:
  selector:
    app: monitoring
  ports:
    - name: http
      port: 9090           # Service port
      targetPort: http     # Container port
  type: ClusterIP
