apiVersion: v1
kind: Service
metadata:
  name: plugin-manager
  namespace: demo-minio-jfrog
spec:
  selector:
    app: plugin-manager
  ports:
    - name: http
      port: 8181           # Service port
      targetPort: http     # Container port
  type: ClusterIP
